### ISSUE TITLE
cells touching the edge of the image are not handled properly

### ISSUE THREAD

**Issue by jmuhlich** [labsyspharm/cellcutter#12]
There is some array slicing/broadcasting bug when a mask is too close to the edge of the image, at least the right and bottom edges. I worked around this by padding the right and bottom of the image and the mask with WINDOW_SIZE pixels, but the logic in the code needs to be fixed of course.

```
Traceback (most recent call last):
  File "/home/jmuhlich/miniconda3/envs/work/lib/python3.10/concurrent/futures/process.py", line 246, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/jmuhlich/miniconda3/envs/work/lib/python3.10/site-packages/cellcutter/cut.py", line 133, in cut_cell_range_shared_mem
    cut_cells(
  File "/home/jmuhlich/miniconda3/envs/work/lib/python3.10/site-packages/cellcutter/cut.py", line 50, in cut_cells
    thumbnail = padded_subset(
  File "/home/jmuhlich/miniconda3/envs/work/lib/python3.10/site-packages/cellcutter/utils.py", line 66, in padded_subset
    out[..., s_out[0][0] : s_out[0][1], s_out[1][0] : s_out[1][1]] = img[
ValueError: could not broadcast input array from shape (4,0,16) into shape (4,14,16)
```

**Comment by clemenshug** [comment]
Thank you @jmuhlich! Should be fixed now.
